# This is a basic workflow to help you get started with Actions
name: Impresi贸n en consola de Linux

on:
  push:
    branches:
      - test_1

jobs:
  print_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Imprimir mensajes
        run: |
          echo "Impresi贸n 1"
          echo "Impresi贸n 2"
          echo "Impresi贸n 3"

